
web:
  replicas: 1
  memoryLimit: 1000Mi
  cpuLimit: 500m
  cpuRequest: 50m
  memoryRequest: 50Mi
  image: artifacts.plane.so/makeplane/plane-frontend
  pullPolicy: Always
  assign_cluster_ip: false
  labels: {}
  annotations: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

admin:
  replicas: 1
  memoryLimit: 1000Mi
  cpuLimit: 500m
  cpuRequest: 50m
  memoryRequest: 50Mi
  image: artifacts.plane.so/makeplane/plane-admin
  pullPolicy: Always
  assign_cluster_ip: false
  labels: {}
  annotations: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

live:
  replicas: 1
  memoryLimit: 1000Mi
  cpuLimit: 500m
  cpuRequest: 50m
  memoryRequest: 50Mi
  image: artifacts.plane.so/makeplane/plane-live
  pullPolicy: Always
  assign_cluster_ip: false
  labels: {}
  annotations: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

api:
  replicas: 1
  memoryLimit: 1000Mi
  cpuLimit: 500m
  cpuRequest: 50m
  memoryRequest: 50Mi
  image: artifacts.plane.so/makeplane/plane-backend
  pullPolicy: Always
  assign_cluster_ip: false
  labels: {}
  annotations: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

worker:
  replicas: 1
  memoryLimit: 1000Mi
  cpuLimit: 500m
  cpuRequest: 50m
  memoryRequest: 50Mi
  image: artifacts.plane.so/makeplane/plane-backend
  pullPolicy: Always
  labels: {}
  annotations: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

beatworker:
  replicas: 1
  memoryLimit: 1000Mi
  cpuLimit: 500m
  cpuRequest: 50m
  memoryRequest: 50Mi
  image: artifacts.plane.so/makeplane/plane-backend
  pullPolicy: Always
  labels: {}
  annotations: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

external_secrets:
  vault_name: pmxp-app-secrets

istio:
  gateway: pmxp-gateway

env:
  web_url: "https://pmxp.io"
  api_url: "https://api.pmxp.io"
  admin_url: "https://admin.pmxp.io"
  live_url: "https://live.pmxp.io"
