
apiVersion: batch/v1
kind: Job
metadata:
  namespace: twsss
  name: pmxp-api-migrate-{{ .Release.Revision }}
  {{- template "plane.labelsAndAnnotations" .Values.api }}
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app.name: twsss-pmxp-api-migrate
      annotations:
        timestamp: {{ now | quote }}
    spec:
      containers:
      - name: pmxp-api-migrate
        image: {{ .Values.api.image }}
        command: 
          - ./bin/docker-entrypoint-migrator.sh
        imagePullPolicy: {{ .Values.api.pullPolicy | default "Always" }}
        envFrom:
          - configMapRef:
              name: pmxp-app-vars
              optional: false
          - secretRef:
              name: {{ .Values.external_secrets.vault_name }}
              optional: false
      restartPolicy: OnFailure
      serviceAccount: pmxp-srv-account
      serviceAccountName: pmxp-srv-account
      {{- include "plane.podScheduling" .Values.api }}
---
